swagger: "2.0"
info:
  description: "This project is to migrate Ethelon server (which is currently using Laravel 5.6) to Spring boot. Some APIs are not using the standard procedures or good practices but it will be fixed soon. "
  version: "2.0.0"
  title: "Ethelon"
  contact:
    email: "kobearelativo@gmail.com"
host: "petstore.swagger.io"
basePath: "/v2"
tags:
- name: "User Access"
  description: "User access to APIs"
schemes:
- "https"
- "http"  
paths:
  /register:
    post:
      tags:
      - "User Access"
      summary: "Register a new user to the DB "
      description: ""
      operationId: "registerUser"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "email"
        in: "path"
        description: "Email of the user to be reigistered"
        required: true
        type: "string"
      - name: "password"
        in: "path"
        description: "Password of the user to be reigistered"
        required: true
        type: "string"
      - name: "name"
        in: "path"
        description: "Name of the user to be reigistered"
        required: true
        type: "string"
      - name: "role"
        in: "path"
        description: "Role of the user to be reigistered"
        required: true
        type: "string"  
      - name: "location"
        in: "path"
        description: "location of the user to be reigistered"
        required: true
        type: "string"  
      - name: "image_url"
        in: "path"
        description: "Display image url of the user to be reigistered"
        required: true
        type: "string"
      - name: "fcm_token"
        in: "path"
        description: "fcm_token of the user to be reigistered"
        required: true
        type: "string"
      - name: "age"
        in: "path"
        type: "string"    
        description: "Age of the user to be reigistered"
        required: true
      responses:
        200: 
           description: "Status is always 200 (Needs to be fixed)"
           schema:
              $ref: "#/definitions/RegisterResponse"
  /login:
    post:
      tags:
      - "User Access"
      summary: "User login to access APIs"
      description: ""
      operationId: "loginUser"
      consumes:
      - "application/json"
      produces:
      - "application/json"    
      parameters:
      - name: "email"
        in: "path"
        description: "Email of the user to login"
        required: true
        type: "string"
      - name: "password"
        in: "path"
        description: "Password of the user to login"
        required: true
        type: "string"
      responses:
        200:
           description: "Status is always 200 (Needs to be fixed)"
           schema:
              $ref: "#/definitions/LoginResponse"            
securityDefinitions:
  petstore_auth:
    type: "oauth2"
    authorizationUrl: "http://petstore.swagger.io/oauth/dialog"
    flow: "implicit"
    scopes:
      write:pets: "modify pets in your account"
      read:pets: "read your pets"
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"
definitions:
  RegisterResponse:
    type: "object"
    properties:
      api_token:
        type: "string"
      volunteer_id:
        type: "string"
      name:
        type: "string"
      message:
        type: "string"
  LoginResponse:
    type: "object"
    properties:
      api_token:
        type: "string"
      volunteer_id:
        type: "string"
      name:
        type: "string"
      message:
        type: "string"
      image_url:
        type: "string"
  ApiResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      type:
        type: "string"
      message:
        type: "string"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"